/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class p2 */

#ifndef _Included_p2
#define _Included_p2
#ifdef __cplusplus
extern "C" {
#endif
#undef p2_FOCUS_TRAVERSABLE_UNKNOWN
#define p2_FOCUS_TRAVERSABLE_UNKNOWN 0L
#undef p2_FOCUS_TRAVERSABLE_DEFAULT
#define p2_FOCUS_TRAVERSABLE_DEFAULT 1L
#undef p2_FOCUS_TRAVERSABLE_SET
#define p2_FOCUS_TRAVERSABLE_SET 2L
#undef p2_TOP_ALIGNMENT
#define p2_TOP_ALIGNMENT 0.0f
#undef p2_CENTER_ALIGNMENT
#define p2_CENTER_ALIGNMENT 0.5f
#undef p2_BOTTOM_ALIGNMENT
#define p2_BOTTOM_ALIGNMENT 1.0f
#undef p2_LEFT_ALIGNMENT
#define p2_LEFT_ALIGNMENT 0.0f
#undef p2_RIGHT_ALIGNMENT
#define p2_RIGHT_ALIGNMENT 1.0f
#undef p2_serialVersionUID
#define p2_serialVersionUID -7644114512714619750i64
#undef p2_serialVersionUID
#define p2_serialVersionUID 4613797578919906343i64
#undef p2_INCLUDE_SELF
#define p2_INCLUDE_SELF 1L
#undef p2_SEARCH_HEAVYWEIGHTS
#define p2_SEARCH_HEAVYWEIGHTS 1L
#undef p2_OPENED
#define p2_OPENED 1L
#undef p2_serialVersionUID
#define p2_serialVersionUID 4497834738069338734i64
#undef p2_DEFAULT_CURSOR
#define p2_DEFAULT_CURSOR 0L
#undef p2_CROSSHAIR_CURSOR
#define p2_CROSSHAIR_CURSOR 1L
#undef p2_TEXT_CURSOR
#define p2_TEXT_CURSOR 2L
#undef p2_WAIT_CURSOR
#define p2_WAIT_CURSOR 3L
#undef p2_SW_RESIZE_CURSOR
#define p2_SW_RESIZE_CURSOR 4L
#undef p2_SE_RESIZE_CURSOR
#define p2_SE_RESIZE_CURSOR 5L
#undef p2_NW_RESIZE_CURSOR
#define p2_NW_RESIZE_CURSOR 6L
#undef p2_NE_RESIZE_CURSOR
#define p2_NE_RESIZE_CURSOR 7L
#undef p2_N_RESIZE_CURSOR
#define p2_N_RESIZE_CURSOR 8L
#undef p2_S_RESIZE_CURSOR
#define p2_S_RESIZE_CURSOR 9L
#undef p2_W_RESIZE_CURSOR
#define p2_W_RESIZE_CURSOR 10L
#undef p2_E_RESIZE_CURSOR
#define p2_E_RESIZE_CURSOR 11L
#undef p2_HAND_CURSOR
#define p2_HAND_CURSOR 12L
#undef p2_MOVE_CURSOR
#define p2_MOVE_CURSOR 13L
#undef p2_NORMAL
#define p2_NORMAL 0L
#undef p2_ICONIFIED
#define p2_ICONIFIED 1L
#undef p2_MAXIMIZED_HORIZ
#define p2_MAXIMIZED_HORIZ 2L
#undef p2_MAXIMIZED_VERT
#define p2_MAXIMIZED_VERT 4L
#undef p2_MAXIMIZED_BOTH
#define p2_MAXIMIZED_BOTH 6L
#undef p2_serialVersionUID
#define p2_serialVersionUID 2673458971256075116i64
#undef p2_EXIT_ON_CLOSE
#define p2_EXIT_ON_CLOSE 3L
/*
 * Class:     p2
 * Method:    setDirContent
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_p2_setDirContent
  (JNIEnv *, jobject);

/*
 * Class:     p2
 * Method:    getFileName
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_p2_getFileName
  (JNIEnv *, jobject);

/*
 * Class:     p2
 * Method:    getDate
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_p2_getDate
  (JNIEnv *, jobject);

/*
 * Class:     p2
 * Method:    getIsFile
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_p2_getIsFile
  (JNIEnv *, jobject);

/*
 * Class:     p2
 * Method:    getFileSize
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_p2_getFileSize
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
