/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class p2_Entry */

#ifndef _Included_p2_Entry
#define _Included_p2_Entry
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
